<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Document</title>';
echo '';
echo '<style>';
echo '#title{';
echo 'text-align: center;';
echo '}';
echo '';
echo '#t1 {';
echo 'background-color:skyblue;';
echo 'width:950px;';
echo 'font-size: 20px;';
echo '}';
echo '#t2, .st  {';
echo 'width:900px;';
echo 'height:100px;';
echo 'font-size: 20px;';
echo 'background-color: gray;';
echo 'border: 2px solid rgba(5, 5, 179, 0.819);';
echo 'border-collapse: collapse;';
echo '';
echo '}';
echo 'tr,td{';
echo 'width:950px;';
echo 'height:100px;';
echo 'text-align: center;';
echo '}';
echo '';
echo '</style>';
echo '</head>';
echo '<body>';
echo '<h1 id="title"> DMU 맛집 메뉴</h1>';
echo '<table id="t1" >';
echo '<tr >';
echo '<td> 맛집 리스트</td>';
echo '<td> 리뷰</td>';
echo '<td> 맛집 제보</td>';
echo '</tr>';
echo '';
echo '</table>';
echo '<br><br>';
echo '';
echo '<table id="t2">';
echo '<tr>';
echo '<td class="st"> 한식</td>';
echo '<td class="st"> 일식</td>';
echo '<td class="st"> 중식</td>';
echo '</tr>';
echo '';
echo '<tr>';
echo '<td class="st"> 커피/음료</td>';
echo '<td class="st" rowspan="2"> 패스트푸드</td>';
echo '<td class="st" rowspan="2"> 술집</td>';
echo '</tr>';
echo '<tr>';
echo '<td class="st">기타</td>';
echo '';
echo '';
echo '</tr>';
echo '';
echo '';
echo '';
echo '';
echo '</table>';
echo '';
echo '';
echo '';
echo '</body>';
echo '</html>';
?>

