<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Document</title>';
echo '';
echo '<style>';
echo '#title{';
echo 'text-align: center;';
echo '}';
echo '#t2{';
echo 'width:900px;';
echo 'height:100px;';
echo 'font-size: 20px;';
echo 'background-color: gray;';
echo '';
echo '}';
echo 'table {';
echo 'background-color:skyblue;';
echo 'width:950px;';
echo 'font-size: 20px;';
echo '}';
echo 'tr,td{';
echo 'width:950px;';
echo 'height:100px;';
echo 'text-align: center;';
echo '}';
echo 'table,td{';
echo 'border-bottom: 2px solid blue;';
echo '}';
echo '</style>';
echo '</head>';
echo '<body>';
echo '<h1 id="title"> DMU 맛집 메뉴</h1>';
echo '<table>';
echo '<tr>';
echo '<td> 맛집 리스트</td>';
echo '<td> 리뷰</td>';
echo '<td> 맛집 제보</td>';
echo '</tr>';
echo '';
echo '</table>';
echo '<br><br>';
echo '';
echo '<table id="t2">';
echo '<tr>';
echo '<td> 한식</td>';
echo '<td> 음식점 명</td>';
echo '<td> 평점</td>';
echo '</tr>';
echo '';
echo '<tr>';
echo '<td> 한식</td>';
echo '<td> 음식점 명</td>';
echo '<td> 평점</td>';
echo '</tr>';
echo '';
echo '<tr>';
echo '<td> 한식</td>';
echo '<td> 음식점 명</td>';
echo '<td> 평점</td>';
echo '</tr>';
echo '</tr>';
echo '';
echo '</table>';
echo '';
echo '';
echo '';
echo '</body>';
echo '</html>';
?>

